openai_api_key: ${openai-api-key}
connections:
  - name: bigquery
    databaseName: ${db-project-bigquery}
    schemaName: ${db-dataset-bigquery}
    dbType: bigquery
    url: >-
      jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=${db-project-bigquery};OAuthType=0;OAuthServiceAcctEmail=${db-bigquery-email-bigquery};OAuthPvtKeyPath=${db-bigquery-bigquery};
